Delete http://localhost:3003/api/blogs/691261336cecf0b1aa858937
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBla2thIiwiaWQiOiI2OTExY2ZhNDg0MjY0MDk0YzViMzUwOGQiLCJpYXQiOjE3NjI4MTE5MzV9.aVOM5GheUw0wsRqsGcfLUgFBgeN3hWgWXaNm89qeCYI