POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "edem@mail.com",
	"name": "Edem Quashigah",
	"password": "password"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "kafui@mail.com",
	"name": "Kafui Quashigah",
	"password": "password"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "fafa@mail.com",
	"name": "Fafa Quashigah",
	"password": "password",
	"disabled": true

}

###
PUT http://localhost:3001/api/users/fafa@mail.com
Content-Type: application/json

{
	"disabled": true

}