POST http://localhost:3001/api/blogs
Content-Type: application/json

{
	"title": "LinkedIn Profile",
	"url": "https://www.linkedin.com/in/edemq/",
	"author": "KoblaQ"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json


{
	"hello": "world"
}

###
PUT http://localhost:3001/api/blogs/8
Content-Type: application/json

{
	"likes": 1
}


###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthZnVpQG1haWwuY29tIiwiaWQiOjQsImlhdCI6MTc3NzMwMjI0Mn0.vY-_TEFpt48iKlkPqHL8udqJJUC9p2H2ey0MyjnNbZg

{
	"title": "This blog is about Edem",
	"url": "https://www.linkedin.com/in/edemq/",
	"author": "Kobla Coder"
}

