POST http://localhost:3001/api/blogs
Content-Type: application/json

{
	"title": "LinkedIn Profile",
	"url": "https://www.linkedin.com/in/edemq/",
	"author": "KoblaQ"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
	"hello": "world"
}

###
PUT http://localhost:3001/api/blogs/8
Content-Type: application/json

{
	"likes": 1
}

