POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "KoblaQ",
	"name": "Kobla Quashigah",
	"password": "password"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "EdemQ",
	"name": "Edem Quashigah",
	"password": "password"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "KoblaQ",
	"name": "Kobla Coder",
	"password": "password"

}

###
PUT http://localhost:3001/api/users/KoblaQ
Content-Type: application/json

{
	"name": "Kobla Coder"

}