GET http://localhost:3001/api/blogs
Content-Type: application/json

###
GET http://localhost:3001/api/blogs/1
Content-Type: application/json


###
GET http://localhost:3001/api/blogs/44
Content-Type: application/json


