POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "KoblaQ",
	"name": "Kobla Quashigah",
	"password": "secret",
	"admin": false
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "EdemQ",
	"name": "Edem Coder",
	"password": "secret",
	"admin": true
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "Ed",
	"name": "Kobla Coder",
	"password": "password"

}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "EdemQ",
	"name": "Edem Coder",
	"password": "secret"

}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "Pekka",
	"name": "Pekka Pekkonen",
	"admin": false,
	"disabled": true,
	"password": "secret"

}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
	"username": "Kafui",
	"name": "Kafui Pekkonen",
	"admin": true,
	"disabled": false,
	"password": "secret"

}