GET http://localhost:3001/api/notes
Content-Type: application/json

###
GET http://localhost:3001/api/notes/1
Content-Type: application/json


###
GET http://localhost:3001/api/notes/44
Content-Type: application/json


