post http://localhost:3001/api/login 
Content-Type: application/json 

{
	"username": "EdemQ",
	"password": "secret"
}

### 
post http://localhost:3001/api/login 
Content-Type: application/json 

{
	"username": "Pekka",
	"password": "secret"
}

### 
post http://localhost:3001/api/login 
Content-Type: application/json 

{
	"username": "KoblaQ",
	"password": "secret"
}